# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Package (PyTorch Practices)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run all Python scripts
        run: |
          echo "Running all Python scripts in the repo..."
          for file in $(find . -name "*.py"); do
            echo "Executing $file"
            python "$file" || exit 1
          done

